name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Run Tests
      run: ./gradlew clean test

    - name: Store reports
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: |
          **/build/reports/
          **/build/test-results/

  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests and export results
        run: |
          postman collection run "31611889-68f7600e-2d37-4575-a01f-4160cedf058e" --reporters cli,json --reporter-json-export result.json
      - name: Upload API test results
        uses: actions/upload-artifact@v3
        with:
          name: postman-results
          path: result.json
