name: Run tests and publish report
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Run tests
        run: ./gradlew clean test

      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        with:
          continue on error: true
          ref: gh-pages
          path: gh-pages
          persist-credentials: false

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          continue on error: true
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Newman and htmlextra
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Run API tests with htmlextra reporter
        run: |
          newman run "https://api.getpostman.com/collections/31611889-68f7600e-2d37-4575-a01f-4160cedf058e?apikey=${{ secrets.POSTMAN_API_KEY }}" --reporters cli,htmlextra --reporter-htmlextra-export html-report.html
      - name: Preview HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: postman-html-report
          path: html-report.html

        
